[package]
name = "german_dictionary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdict = "0.1.1"
regex = "1.10.2"
utf16_reader = "0.1.0"
